# Generated by Django 4.2.17 on 2024-12-20 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=25)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('preferences_alimentaires', models.JSONField(null=True)),
                ('preferences_sonore', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bailleur',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cible.client')),
                ('cni', models.CharField(max_length=20, verbose_name='immatriculation de la cni')),
                ('presentation', models.TextField(max_length=150, verbose_name='une brieve presentation du bailleur')),
            ],
            bases=('cible.client',),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=500)),
                ('not_client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_client', to='cible.client')),
                ('not_bailleur_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_bailleur', to='cible.bailleur')),
            ],
        ),
    ]
